@startuml
'https://plantuml.com/class-diagram

class Voltage220V{
+output220V():int
}

interface Voltage5V{
+output5V():int
}

class VoltageAdapter extends Voltage220V implements Voltage5V{

}

class Phone{
+charging():void
}

Phone ..> Voltage5V

Client ..>Phone
Client ..>Voltage220V

@enduml