@startuml
'https://plantuml.com/class-diagram

interface java.sql.Connection
interface com.mysql.jdbc.Connection
interface MySQLConnection
Class ConnectionImpl implements MySQLConnection
DriverManager ..> java.sql.Connection
Client ..> DriverManager

com.mysql.jdbc.Connection --|> java.sql.Connection
MySQLConnection --|>com.mysql.jdbc.Connection

@enduml