@startuml
'https://plantuml.com/class-diagram

title Strategy 策略模式

class CashContext{
    -CashSuper cs;
    +CashContext(String type);
    +double getResult(double money);
}

interface CashSuper{
    +double acceptCash(double money);
}

class CashDiscount extends CashSuper{
    -double moneyDiscount;
    +double acceptCash(double money);
}

class CashNormal extends CashSuper{
    +double acceptCash(double money);
}

class CashReturn extends CashSuper{
    -double moneyCondition;
    -double moneyReturn;
    +double acceptCash(double money);
}


CashContext - CashSuper: create >



@enduml